USE [master]
GO

USE [Tyler1]

GO 
/****** Object:  Database [Tyler1]    Script Date: 28/08/2017 09:50:05 p.m. ******/
CREATE DATABASE [Tyler1]
GO

ALTER DATABASE [Tyler1] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Tyler1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Tyler1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Tyler1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Tyler1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Tyler1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Tyler1] SET ARITHABORT OFF 
GO

ALTER DATABASE [Tyler1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Tyler1] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Tyler1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Tyler1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Tyler1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Tyler1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Tyler1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Tyler1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Tyler1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Tyler1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Tyler1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Tyler1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Tyler1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Tyler1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Tyler1] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Tyler1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Tyler1] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Tyler1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Tyler1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Tyler1] SET  MULTI_USER 
GO

ALTER DATABASE [Tyler1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Tyler1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Tyler1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Tyler1] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Tyler1] SET  READ_WRITE 
GO


