CREATE DATABASE DULCERIA_DB;
GO

USE DULCERIA_DB; 
GO



select * from FABRICANTES
select * from PROVEEDORES
select * from FORMAS_PAGOS
select * from ESTATUS
select * from SUCURSALES
select * from CATEGORIAS
select * from CLIENTES
select * from ARTICULOS
select * from EMPLEADOS
select * from DETALLE_VENTAS
select * from DETALLES_ARTICULOS
select * from VENTAS
select * from FACTURACIONES
select * from CANCELACIONES

--CREACION DE LAS TABLAS!!!!!


create table prueba( ID_PRUEBA INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(20)  NOT NULL  ,
  DESCRIPCION VARCHAR(150)      ,
PRIMARY KEY(ID_PRUEBA));
GO

CREATE TABLE FABRICANTES (
  ID_FABRICANTE INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(20)  NOT NULL  ,
  DESCRIPCION VARCHAR(150)      ,
PRIMARY KEY(ID_FABRICANTE));
GO

CREATE TABLE PROVEEDORES (
  ID_PROVEEDOR INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(15)  NOT NULL  ,
  TELEFONO VARCHAR(15)  NOT NULL  ,
  CORREO VARCHAR(50)  NOT NULL  ,
  DIRECCION VARCHAR(100)      ,
PRIMARY KEY(ID_PROVEEDOR));
GO

CREATE TABLE FORMAS_PAGOS (
  ID_FORMA_PAGO INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(30)  NOT NULL  ,
  SERIE VARCHAR(100)      ,
PRIMARY KEY(ID_FORMA_PAGO));
GO

CREATE TABLE ESTATUS (
  ID_ESTATUS INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(20)  NOT NULL  ,
  DESCRIPCION VARCHAR(150)      ,
PRIMARY KEY(ID_ESTATUS));
GO

CREATE TABLE SUCURSALES (
  ID_SUCURSAL INTEGER  NOT NULL   IDENTITY ,
  DIRECCION VARCHAR(100)  NOT NULL  ,
  TELEFONO VARCHAR(15)  NOT NULL  ,
  RESPONSABLE VARCHAR(50)  NOT NULL    ,
PRIMARY KEY(ID_SUCURSAL));
GO

CREATE TABLE CATEGORIAS (
  ID_CATEGORIA INTEGER  NOT NULL   IDENTITY ,
  NOMBRE VARCHAR(20)  NOT NULL  ,
  DESCRIPCION VARCHAR(150)      ,
PRIMARY KEY(ID_CATEGORIA));
GO

CREATE TABLE CLIENTES (
  ID_CLIENTE INTEGER  NOT NULL   IDENTITY ,
  ESTATUS_ID_ESTATUS INTEGER    ,
  NOMBRE VARCHAR(30)  NOT NULL  ,
  APELLIDOS VARCHAR(30)  NOT NULL  ,
  EMAIL VARCHAR(50)  NOT NULL  ,
  RFC VARCHAR(20)    ,
  DIRECCION VARCHAR(100)  NOT NULL  ,
  TELEFONO VARCHAR(15)      ,
PRIMARY KEY(ID_CLIENTE)  ,
  FOREIGN KEY(ESTATUS_ID_ESTATUS)
    REFERENCES ESTATUS(ID_ESTATUS)
      ON DELETE CASCADE
      ON UPDATE CASCADE);
GO

CREATE INDEX CLIENTES_FK_ESTATUS ON CLIENTES (ESTATUS_ID_ESTATUS);
GO

CREATE INDEX IFK_1_1 ON CLIENTES (ESTATUS_ID_ESTATUS);
GO

CREATE TABLE ARTICULOS (
  ID_ARTICULO INTEGER  NOT NULL   IDENTITY ,
  FABRICANTE_ID_FABRICANTE INTEGER  NOT NULL  ,
  CATEGORIA_ID_CATEGORIA INTEGER  NOT NULL  ,
  NOMBRE VARCHAR(30)  NOT NULL  ,
  DESCRIPCION VARCHAR(150)  NOT NULL  ,
  CODIGO VARCHAR(15)  NOT NULL  ,
  PRECIO DECIMAL(5,2)  NOT NULL  ,
  CANTIDAD INTEGER  NOT NULL    ,
PRIMARY KEY(ID_ARTICULO)      ,
  FOREIGN KEY(CATEGORIA_ID_CATEGORIA)
    REFERENCES CATEGORIAS(ID_CATEGORIA)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(FABRICANTE_ID_FABRICANTE)
    REFERENCES FABRICANTES(ID_FABRICANTE)
      ON DELETE CASCADE
      ON UPDATE CASCADE);
GO

CREATE UNIQUE INDEX ARTICULOS_UQ_CODIGO ON ARTICULOS (CODIGO);
GO
CREATE INDEX ARTICULOS_FK_CATEGORIA ON ARTICULOS (CATEGORIA_ID_CATEGORIA);
GO
CREATE INDEX ARTICULOS_FK_FABRICANTE ON ARTICULOS (FABRICANTE_ID_FABRICANTE);
GO

CREATE INDEX IFK_N_1 ON ARTICULOS (CATEGORIA_ID_CATEGORIA);
GO
CREATE INDEX IFK_1_1 ON ARTICULOS (FABRICANTE_ID_FABRICANTE);
GO

CREATE TABLE EMPLEADOS (
  ID_EMPLEADO INTEGER  NOT NULL   IDENTITY ,
  ESTATUS_ID_ESTATUS INTEGER  NOT NULL  ,
  SUCURSAL_ID_SUCURSAL INTEGER  NOT NULL  ,
  NOMBRE VARCHAR(30)  NOT NULL  ,
  APELLIDOS VARCHAR(30)  NOT NULL  ,
  FEC_NAC DATE    ,
  EMAIL VARCHAR(50)  NOT NULL  ,
  TELEFONO VARCHAR(15)    ,
  SUELDO DECIMAL(7,2)  NOT NULL  ,
  PUESTO VARCHAR(30)  NOT NULL    ,
PRIMARY KEY(ID_EMPLEADO)    ,
  FOREIGN KEY(SUCURSAL_ID_SUCURSAL)
    REFERENCES SUCURSALES(ID_SUCURSAL)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(ESTATUS_ID_ESTATUS)
    REFERENCES ESTATUS(ID_ESTATUS)
      ON DELETE CASCADE
      ON UPDATE CASCADE);
GO

CREATE INDEX EMPLEADOS_FK_SUCURSAL ON EMPLEADOS (SUCURSAL_ID_SUCURSAL);
GO
CREATE INDEX EMPLEADOS_FK_ESTATUS ON EMPLEADOS (ESTATUS_ID_ESTATUS);
GO

CREATE INDEX IFK_1_N ON EMPLEADOS (SUCURSAL_ID_SUCURSAL);
GO
CREATE INDEX IFK_1_1 ON EMPLEADOS (ESTATUS_ID_ESTATUS);
GO

CREATE TABLE DETALLES_ARTICULOS (
  ID_INVENTARIO INTEGER  NOT NULL   IDENTITY ,
  PROVEEDOR_ID_PROVEEDOR INTEGER  NOT NULL  ,
  ESTATUS_ID_ESTATUS INTEGER  NOT NULL  ,
  ARTICULO_ID_ARTICULO INTEGER  NOT NULL    ,
PRIMARY KEY(ID_INVENTARIO)      ,
  FOREIGN KEY(ARTICULO_ID_ARTICULO)
    REFERENCES ARTICULOS(ID_ARTICULO)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(ESTATUS_ID_ESTATUS)
    REFERENCES ESTATUS(ID_ESTATUS)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(PROVEEDOR_ID_PROVEEDOR)
    REFERENCES PROVEEDORES(ID_PROVEEDOR)
      ON DELETE CASCADE
      ON UPDATE CASCADE);
GO

CREATE INDEX DETALLES_ARTICULOS_FK_ARTICULO ON DETALLES_ARTICULOS (ARTICULO_ID_ARTICULO);
GO
CREATE INDEX DETALLES_ARTICULOS_FK_ESTATUS ON DETALLES_ARTICULOS (ESTATUS_ID_ESTATUS);
GO
CREATE INDEX DETALLES_ARTICULOS_FK_PROVEEDOR ON DETALLES_ARTICULOS (PROVEEDOR_ID_PROVEEDOR);
GO

CREATE INDEX IFK_1_1 ON DETALLES_ARTICULOS (ARTICULO_ID_ARTICULO);
GO
CREATE INDEX IFK2_1_1 ON DETALLES_ARTICULOS (ESTATUS_ID_ESTATUS);
GO
CREATE INDEX IFK3_1_1 ON DETALLES_ARTICULOS (PROVEEDOR_ID_PROVEEDOR);
GO

CREATE TABLE VENTAS (
  ID_VENTA INTEGER  NOT NULL   IDENTITY ,
  ARTICULO_ID_ARTICULO INTEGER  NOT NULL  ,
  FECHA DATE  NOT NULL  ,
  TOTAL DECIMAL(6,2)  NOT NULL  ,
  SUBTOTAL DECIMAL(6,2)  NOT NULL  ,
  CANTIDAD INTEGER  NOT NULL  ,
  PRECIO DECIMAL(5,2)  NOT NULL    ,
PRIMARY KEY(ID_VENTA)  ,
  FOREIGN KEY(ARTICULO_ID_ARTICULO)
    REFERENCES ARTICULOS(ID_ARTICULO)
      ON DELETE CASCADE
      ON UPDATE CASCADE);
GO

CREATE INDEX VENTAS_FK_ARTICULO ON VENTAS (ARTICULO_ID_ARTICULO);
GO

CREATE INDEX IFK_1_N ON VENTAS (ARTICULO_ID_ARTICULO);
GO

CREATE TABLE DETALLE_VENTAS (
  ID_DETALLE_VENTA INTEGER  NOT NULL   IDENTITY ,
  SUCURSAL_ID_SUCURSAL INTEGER  NOT NULL  ,
  EMPLEADO_ID_EMPLEADO INTEGER  NOT NULL  ,
  VENTA_ID_VENTA INTEGER  NOT NULL    ,
PRIMARY KEY(ID_DETALLE_VENTA)      ,
  FOREIGN KEY(VENTA_ID_VENTA)
    REFERENCES VENTAS(ID_VENTA)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(EMPLEADO_ID_EMPLEADO)
    REFERENCES EMPLEADOS(ID_EMPLEADO)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(SUCURSAL_ID_SUCURSAL)
    REFERENCES SUCURSALES(ID_SUCURSAL));
GO

CREATE INDEX DETALLES_VENTA_FK_VENTA ON DETALLE_VENTAS (VENTA_ID_VENTA);
GO
CREATE INDEX DETALLES_VENTA_FK_EMPLEADO ON DETALLE_VENTAS (EMPLEADO_ID_EMPLEADO);
GO
CREATE INDEX DETALLE_VENTAS_FK_SUCURSAL ON DETALLE_VENTAS (SUCURSAL_ID_SUCURSAL);
GO

CREATE INDEX IFK_1_A_1 ON DETALLE_VENTAS (VENTA_ID_VENTA);
GO
CREATE INDEX IFK_1_A_1_ ON DETALLE_VENTAS (EMPLEADO_ID_EMPLEADO);
GO
CREATE INDEX IFK_1_A_1__ ON DETALLE_VENTAS (SUCURSAL_ID_SUCURSAL);
GO

CREATE TABLE FACTURACIONES (
  ID_FACTURACION INTEGER  NOT NULL   IDENTITY ,
  FORMAS_PAGO_ID_FORMA_PAGO INTEGER  NOT NULL  ,
  EMPLEADO_ID_EMPLEADO INTEGER  NOT NULL  ,
  VENTA_ID_VENTA INTEGER  NOT NULL  ,
  CLIENTE_ID_CLIENTE INTEGER  NOT NULL  ,
  FECHA DATE  NOT NULL    ,
PRIMARY KEY(ID_FACTURACION)        ,
  FOREIGN KEY(CLIENTE_ID_CLIENTE)
    REFERENCES CLIENTES(ID_CLIENTE)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(FORMAS_PAGO_ID_FORMA_PAGO)
    REFERENCES FORMAS_PAGOS(ID_FORMA_PAGO)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(VENTA_ID_VENTA)
    REFERENCES VENTAS(ID_VENTA)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(EMPLEADO_ID_EMPLEADO)
    REFERENCES EMPLEADOS(ID_EMPLEADO));
GO

CREATE INDEX FACTURACIONES_FK_CLIENTE ON FACTURACIONES (CLIENTE_ID_CLIENTE);
GO
CREATE INDEX FACTURACIONES_FK_FORMAS_PAGO ON FACTURACIONES (FORMAS_PAGO_ID_FORMA_PAGO);
GO
CREATE INDEX FACTURACIONES_FK_VENTA ON FACTURACIONES (VENTA_ID_VENTA);
GO
CREATE INDEX FACTURACIONES_FKIndex4 ON FACTURACIONES (EMPLEADO_ID_EMPLEADO);
GO

CREATE INDEX IFK_N_1 ON FACTURACIONES (CLIENTE_ID_CLIENTE);
GO
CREATE INDEX IFK_1_1 ON FACTURACIONES (FORMAS_PAGO_ID_FORMA_PAGO);
GO
CREATE INDEX IFK_1_A_1 ON FACTURACIONES (VENTA_ID_VENTA);
GO
CREATE INDEX IFK_1_A_1_ ON FACTURACIONES (EMPLEADO_ID_EMPLEADO);
GO

CREATE TABLE CANCELACIONES (
  ID_CANCELACION INTEGER  NOT NULL   IDENTITY ,
  SUCURSAL_ID_SUCURSAL INTEGER  NOT NULL  ,
  DETALLE_VENTA_ID_DETALLE_VENTA INTEGER  NOT NULL  ,
  EMPLEADO_ID_EMPLEADO INTEGER  NOT NULL  ,
  MOTIVO VARCHAR(150)  NOT NULL    ,
PRIMARY KEY(ID_CANCELACION)      ,
  FOREIGN KEY(EMPLEADO_ID_EMPLEADO)
    REFERENCES EMPLEADOS(ID_EMPLEADO),
  FOREIGN KEY(DETALLE_VENTA_ID_DETALLE_VENTA)
    REFERENCES DETALLE_VENTAS(ID_DETALLE_VENTA),
  FOREIGN KEY(SUCURSAL_ID_SUCURSAL)
    REFERENCES SUCURSALES(ID_SUCURSAL));
GO

CREATE INDEX CANCELACION_FK_EMPLEADO ON CANCELACIONES (EMPLEADO_ID_EMPLEADO);
GO
CREATE INDEX CANCELACION_FK_DETALLE_VENTA ON CANCELACIONES (DETALLE_VENTA_ID_DETALLE_VENTA);
GO
CREATE INDEX CANCELACION_FK_SUCURSAL ON CANCELACIONES (SUCURSAL_ID_SUCURSAL);
GO

CREATE INDEX IFK_1_1 ON CANCELACIONES (EMPLEADO_ID_EMPLEADO);
GO
CREATE INDEX IFK_1_A_1 ON CANCELACIONES (DETALLE_VENTA_ID_DETALLE_VENTA);
GO
CREATE INDEX IFK_1_A_1_ ON CANCELACIONES (SUCURSAL_ID_SUCURSAL);
GO

--INSERCIÓN DE INFORMACIÓN

--ESTATUS
INSERT INTO ESTATUS (NOMBRE)VALUES('ACTIVO');

--CATEGORIAS
INSERT INTO CATEGORIAS VALUES('CHICLES','GOMA DE MASCAR CON SABORIZANTE');
INSERT INTO CATEGORIAS VALUES('PALETAS','BASE DE PLASTICO FIRME Y ALARGADA CON CARAMELO EN LA PUNTA');
INSERT INTO CATEGORIAS VALUES('GOMITAS', 'DULCE SUAVE DE SABOR');
INSERT INTO CATEGORIAS VALUES('CHOCOLATES', 'DULCE SABOR CHOCOLATE CRUJIENTE');
INSERT INTO CATEGORIAS VALUES('POLVOS', 'DULCE PICANTE EN POLVO');

--FABRICANTE
INSERT INTO FABRICANTES VALUES('ADAMS','FABRICANTE DE CHICLES DE COLORES Y SABORES');
INSERT INTO FABRICANTES VALUES('ALEXIS', 'FABRICANTE DE MAZAPN');
INSERT INTO FABRICANTES VALUES('ADRIAN', 'FABRICANTE DE PALETAS');
INSERT INTO FABRICANTES VALUES('JOSE', 'FABRIANTE DE GOMITAS');
INSERT INTO FABRICANTES VALUES('MONICA', 'FABRICANTE DE ALGODONES');

--ARTICULO

INSERT INTO ARTICULOS VALUES(1,1,'BUBBALOO PLATANO','CHICLES SABOR PLATANO MARCA ADAMS 60 PZ','ADM0034',35.50,10);
INSERT INTO ARTICULOS VALUES(1,1,'PALETA PAYASO','PALETA SABOR A CHOCOLATE CON BOMBON 40 PZ','ADM0035',47.50,10);
INSERT INTO ARTICULOS VALUES(1,1,'MAZAPAN AZTECA','MAZA MARCA AZTECA 50 PZ','ADM0036',45.50,10);
INSERT INTO ARTICULOS VALUES(1,1,'BARRA DE CHOCOLATE','BARRA DE CHOCOLATE MARCA HERSHEY 80 PZ','ADM0037',70.50,10);
INSERT INTO ARTICULOS VALUES(1,1,'PANDITAS','DULCE DE GOMA DE VARIOS SABORES MARCA RICOLINO 60 PZ','ADM0038',55.50,10);

--PROVEEDOR
INSERT INTO PROVEEDORES (NOMBRE, TELEFONO, CORREO)VALUES('ADAMAS FACTORY','012-125-5858','ADAMS.FACTORY@ADAMS.COM');
INSERT INTO PROVEEDORES (NOMBRE, TELEFONO, CORREO)VALUES('HERSHEY FACTORY','012-125-5858','HERSHEY.FACTORY@HERSHEY.COM');
INSERT INTO PROVEEDORES (NOMBRE, TELEFONO, CORREO)VALUES('AZTECA FACTORY','012-125-5858','AZTECA.FACTORY@AZTECA.COM');

--DETALLES DEL ARTICULO
INSERT INTO DETALLES_ARTICULOS VALUES(1,1,1);


--VENTA
INSERT INTO VENTAS VALUES(1,'07/11/2017',41.18,55.50,1,35.50);
INSERT INTO VENTAS VALUES(1,'08/05/2016',55.19,28.50,1,48.50);
INSERT INTO VENTAS VALUES(1,'07/03/2016',66.20,31.50,1,98.50);
INSERT INTO VENTAS VALUES(1,'02/12/2017',74.21,44.50,1,12.50);
INSERT INTO VENTAS VALUES(1,'06/01/2017',10.22,55.50,1,46.50);

--FORMAS DE PAGO
INSERT INTO FORMAS_PAGOS (NOMBRE)VALUES('EFECTIVO');
INSERT INTO FORMAS_PAGOS (NOMBRE)VALUES('TARJETA DE CREDITO');
INSERT INTO FORMAS_PAGOS (NOMBRE)VALUES('BITCOINS');

--CLIENTES
INSERT INTO CLIENTES (ESTATUS_ID_ESTATUS,NOMBRE,APELLIDOS,EMAIL,TELEFONO,DIRECCION)VALUES(1,'BRANDON','CASTILLO','JCASTILLO.BRANDON@GMAIL.COM','8111860118','AV. SIEMPRE VIVA 742');
INSERT INTO CLIENTES (ESTATUS_ID_ESTATUS,NOMBRE,APELLIDOS,EMAIL,TELEFONO,DIRECCION)VALUES(1,'ALEXIS','LOPEZ','ADRIANLOPEZVINE@GMAIL.COM','8120937138','AV. PEPERONI Y SALAMI');
INSERT INTO CLIENTES (ESTATUS_ID_ESTATUS,NOMBRE,APELLIDOS,EMAIL,TELEFONO,DIRECCION)VALUES(1,'ALEXIS','VILLARREAL','ALEXISVILLA@GMAIL.COM','8151968748','AV. JAMON Y PAN');
INSERT INTO CLIENTES (ESTATUS_ID_ESTATUS,NOMBRE,APELLIDOS,EMAIL,TELEFONO,DIRECCION)VALUES(1,'MARCO','PEREZ','MARCP@GMAIL.COM','819851951','AV. HOJALA Y LAMINA');
INSERT INTO CLIENTES (ESTATUS_ID_ESTATUS,NOMBRE,APELLIDOS,EMAIL,TELEFONO,DIRECCION)VALUES(1,'ALEXIS','NEWTON','ADRINEWTON@GMAIL.COM','884571945','AV. HERRADURA');

--SUCURSAL
INSERT INTO SUCURSALES VALUES('EDUARDO LIVAS 133','012-395-6789','HOMERO J. SIMPSON');
INSERT INTO SUCURSALES VALUES('EUGENIO GARZA 144','489-167-2164','JAIR MEDRANO VALERIO');
INSERT INTO SUCURSALES VALUES('HEBERARDO GARCIA 155','731-816-1648','DANIEL JIMENEZ NUÑEZ');
INSERT INTO SUCURSALES VALUES('AGUSTIN SIMDIONA 166','164-846-8164','CHRISTOPHER AVILEZ');
INSERT INTO SUCURSALES VALUES('CARLOS HERNANDEZ 177','861-318-8164','MARIO GONZALEZ');

--EMPLEADO
INSERT INTO EMPLEADOS VALUES(1,1,'JOSE','LOPEZ PEREZ','07/11/1980','PEREZ.JOSE@GMAIL.COM','987-654-3210',15000.00,'JEFE DE SUCURSAL');
INSERT INTO EMPLEADOS VALUES(1,1,'MARIO','MEDRANO VALERIO','08/12/1990','MEDRANO.J@GMAIL.COM','987-841-3210',16000.00,'GERENTE DE TIENDA');
INSERT INTO EMPLEADOS VALUES(1,1,'JAIR','AGUILAR','09/13/1985','AGUILAR@GMAIL.COM','987-619-3210',17000.00,'ACOMODADOR DE PAQUETERIA');
INSERT INTO EMPLEADOS VALUES(1,1,'DANIEL','JIMENEZ NUÑEZ','10/14/1950','DANNNYJ@GMAIL.COM','987-894-3210',18000.00,'ENCARGADO DE CAJA');
INSERT INTO EMPLEADOS VALUES(1,1,'ENRIQUE','ALAMILLO','11/15/1970','ALAMILLO@GMAIL.COM','987-164-3210',19000.00,'LMAO');

--FACTURACION
INSERT INTO FACTURACIONES VALUES(1,1,1,1,'07/11/2017');

--DETALLE DE LA VENTA
INSERT INTO DETALLE_VENTAS VALUES(1,1,1);

--CANCELACIÓN
INSERT INTO CANCELACIONES VALUES(1,1,1,'RECHAZO DE PRODUCTO POR EL CLIENTE');
INSERT INTO CANCELACIONES VALUES(1,1,1,'PRODUCTO EN MAL ESTADO');

--COMPROBACION DE LOS DATOS DE LAS TABLAS




--CATEGORIAS------------------------------------------------------

--SELECT 
select * from CATEGORIAS
select * from CATEGORIAS where NOMBRE='CHICLES' order by ID_CATEGORIA
--UPDATE
update CATEGORIAS set NOMBRE='PICOSITO' where NOMBRE='POLVOS'
--DELETE
delete from CATEGORIAS where NOMBRE='PICOSITO'
--VIEW

create view VISTACATEGORIA as
select * from CATEGORIAS where ID_CATEGORIA = 5

select * from VISTACATEGORIA

--FABRICANTE------------------------------------------------------

--SELECT 
select * from FABRICANTES
select * from FABRICANTES where NOMBRE='ALEXIS' order by ID_FABRICANTE
--UPDATE
update FABRICANTES set NOMBRE='ADRIAN' where NOMBRE='ALEXIS'
--DELETE
delete from FABRICANTES where NOMBRE='ADRIAN' or NOMBRE='MONICA'
--VIEW
create view VISTAFABRICANTE as
select * from FABRICANTES where ID_FABRICANTE = 7

select * from VISTAFABRICANTE

--ARTICULO------------------------------------------------------

--SELECT 
select * from ARTICULOS
select * from ARTICULOS where NOMBRE='PANDITAS' order by ID_ARTICULO
--UPDATE
update ARTICULOS set NOMBRE='PANDA GOMITA' where NOMBRE='PANDITAS'
--DELETE
delete from ARTICULOS where NOMBRE='MAZAPAN AZTECA' or NOMBRE='PANDA GOMITA'
--VIEW
create view VISTA_ARTICULO as
select * from ARTICULOS where ID_ARTICULO = 9

select * from VISTA_ARTICULO

--PROVEEDOR------------------------------------------------------

--SELECT 
select * from PROVEEDORES
select * from PROVEEDORES where NOMBRE='ADAMAS FACTORY' order by ID_PROVEEDOR
--UPDATE
update PROVEEDORES set NOMBRE= 'DIANA FACTORY' where NOMBRE='ADANA FACTORY'
--DELETE
delete from PROVEEDORES where NOMBRE='AZTECA FACTORY'
--VIEW
create view VISTAPROVEEDORES as
select * from PROVEEDORES where ID_PROVEEDOR = 8

select * from VISTAPROVEEDORES

--VENTAS------------------------------------------------------

--SELECT 
select * from VENTAS
select * from VENTAS where TOTAL=41.18 order by ID_VENTA
--UPDATE
update VENTAS set SUBTOTAL=29.50 where SUBTOTAL=35.50
--DELETE
delete from VENTAS where TOTAL=55.19
--VIEW
create view VISTAVENTAS as
select * from VENTAS where ID_VENTA = 6

select * from VISTAVENTAS


--CLIENTES------------------------------------------------------

--SELECT 
select * from CLIENTES
select * from CLIENTES where NOMBRE='ALEXIS' order by ID_CLIENTE
--UPDATE
update CLIENTES set NOMBRE='ADRIAN' where NOMBRE='ALEXIS'
--DELETE
delete from CLIENTES where APELLIDOS='LOPEZ' or NOMBRE='ALEXIS'
--VIEW
create view VISTACLIENTE as
select * from CLIENTES where ID_CLIENTE = 1

select * from VISTACLIENTE

--SUCURSAL------------------------------------------------------

--SELECT 
select * from SUCURSALES
select * from SUCURSALES where RESPONSABLE='HOMERO J. SIMPSON' order by ID_SUCURSAL
--UPDATE
update SUCURSALES set RESPONSABLE='KYM YUNG UN' where RESPONSABLE='JAIR MEDRANO VALERIO'
--DELETE
delete from SUCURSALES where DIRECCION='EUGENIO GARZA 144'
--VIEW
create view VISTASUCURSAL as
select * from SUCURSALES where ID_SUCURSAL = 5

select * from VISTASUCURSAL


--EMPLEADO------------------------------------------------------

--SELECT 
select * from EMPLEADOS
select * from EMPLEADOS where NOMBRE='JAIR' order by ID_EMPLEADO
--UPDATE
update EMPLEADOS set NOMBRE='JAIR' where NOMBRE='ENRIQUE'
--DELETE
delete from EMPLEADOS where NOMBRE='MARIO'
--JOINS 
SELECT Empleados.Nombre, Empleados.Apellidos, Empleados.ESTATUS_ID_ESTATUS FROM Empleados INNER JOIN Estatus ON Empleados.ESTATUS_ID_ESTATUS=Estatus.ID_Estatus;
--VIEW
create view VISTAEMPLEADO as
select * from EMPLEADOS where ID_EMPLEADO = 6

select * from VISTAEMPLEADO

--PROCEDURE

CREATE PROCEDURE spGetAllEmployees
AS
    SET NOCOUNT ON;
    SELECT Nombre, Apellidos, Puesto, Sueldo, SUCURSAL_ID_SUCURSAL
    FROM EMPLEADOS;
GO

EXEC /*O EXECUTE*/ spGetAllEmployees;
GO

--PROCEDURE

CREATE PROCEDURE spGetVentas
    @Articulo int, 
    @Fecha Date

AS 
    SET NOCOUNT ON;
    SELECT *
    FROM VENTAS
    WHERE ARTICULO_ID_ARTICULO = @Articulo AND FECHA = @Fecha;
GO

EXECUTE spGetVentas N'1', N'2017-07-11';
GO

--PROCEDURE

CREATE PROCEDURE spInsertarProveedor
	@Nombre varchar(15),
	@Telefono varchar(15),
	@Correo varchar(50),
	@Direccion varchar(100)
AS
	INSERT INTO PROVEEDORES
	VALUES(@Nombre,@Telefono,@Correo,@Direccion);
GO

EXEC spInsertarProveedor 'Dulces Vero','0189563225','vero.dulceria@vero.com.mx','Av. Stiva 123, Escobedo NL';
GO

--JOIN

SELECT C.NOMBRE+' '+C.APELLIDOS AS CLIENTE, F.FECHA AS 'FECHA DE FACTURACION', F.FORMAS_PAGO_ID_FORMA_PAGO
FROM CLIENTES C
LEFT OUTER JOIN FACTURACIONES F ON F.CLIENTE_ID_CLIENTE = C.ID_CLIENTE; 


--JOIN

SELECT A.NOMBRE AS ARTICULO, A.DESCRIPCION, A.CODIGO, C.NOMBRE AS CATEGORIA
FROM ARTICULOS A 
INNER JOIN CATEGORIAS C ON A.CATEGORIA_ID_CATEGORIA = C.ID_CATEGORIA
GROUP BY C.NOMBRE, A.DESCRIPCION, A.CODIGO, A.NOMBRE;


--TRIGGER

CREATE TRIGGER updateVentas
ON VENTAS
AFTER UPDATE
AS
if UPDATE(CANTIDAD)
	BEGIN
		UPDATE VENTAS SET FECHA=GETDATE();
	END

UPDATE VENTAS SET CANTIDAD=5;

-- TRIGGER

CREATE TRIGGER mensajeVenta
ON VENTAS
AFTER INSERT, UPDATE
AS
PRINT 'SE INSERTÓ O ELIMINÓ CORRECTAMENTE LA VENTA'
GO